# Site settings
# These are used to personalize your new site.
title: Zachary Wedding # your name here
logo: "/images/Head Shot.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Cybersecurity (class of 2025)
  <br /><br />
  <a href="/pdf/Zachary Wedding Resume.pdf?raw=true">View My Resume</a>
github_username:  zwedding # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

